// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjxbfbfjnjcedzbmynhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqeGJmYmZqbmpjZWR6Ym15bmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDAxNDcsImV4cCI6MjA1NjA3NjE0N30.E0g4Ih61Rs9Lw5n8NAmmOqHJwCv_YYuMmRdeW4rLOdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);